### ISSUE TITLE
isOcluded using distance to determine intersections may not be optimal

### ISSUE THREAD

**Issue by marmottchen** [MarkelZ/pygame-light2d#13]
Hi, I saw your project on reddit and I have to say it's super cool :D 
I don't have any experience with shaders, so I was curious how it worked and read through fragment_light.glsl.
There I noticed that you did:
```
float t=(v2.x*(p.y-fragmentTexCoord.y)+v2.y*(fragmentTexCoord.x-p.x))/crossProduct;
vec2 intersection=p+t*v1;
if(crossProduct==0.){
        return false;
}
if(distance(p,intersection)>lengthV1||distance(q,intersection)>lengthV1){
        return false;// The intersection point is not between p and q
}
if(distance(fragmentTexCoord,intersection)>lengthV2||distance(lightPos,intersection)>lengthV2){
        return false;// The intersection point is not between fragmentTexCoord and lightPos
}
```

You actually don't need to use distance here in the last two checks.
Instead you could check if $0 \leq t \leq 1$ instead of the first check.
Further you could calculate another constant u like t, but with the property that intersection = fragmentTexCoord + u * v2 and check if $0\leq u\leq 1$.

I would imagine that to be faster then distance which needs to square and root stuff.
Wikipedia suggests the same: [Link to the mentioned wikipedia article](https://en.wikipedia.org/wiki/Line%E2%80%93line_intersection#Given_two_points_on_each_line_segment)

There could also be some slight optimizations to the runtime by only computing for the next check, after the last check passed.
You also dont seem to be using the dotProduct.

All together my suggestion is to change the code to:
```
bool isOcluded(vec2 p,vec2 q){
    vec2 v1=q-p;
    vec2 v2=lightPos-fragmentTexCoord;

    float crossProduct=v1.x*v2.y-v1.y*v2.x;
    if(crossProduct==0.){
        return false;
    }
    
    float t=(v2.x*(p.y-fragmentTexCoord.y)+v2.y*(fragmentTexCoord.x-p.x))/crossProduct;
    
    if(t<0||1<t){
        return false;// The intersection point is not between p and q
    }

    float u=(v1.x*(fragmentTexCoord.y-p.y)+v1.y*(p.x-fragmentTexCoord.x))/-crossProduct;
    if(u<0||1<u){
        return false;// The intersection point is not between fragmentTexCoord and lightPos
    }
    return true;
}

```

I don't know if you are actually going to read this, but if you do, I hope I was able to contribute a tiny little bit :D 
Again this project is super cool and definitely motivated me to try out pygame with shaders myself in the future sometime.

**Comment by MarkelZ** [comment]
Hi @marmottchen! Thank you so much :)) I included these changes in [ebd20fc](https://github.com/MarkelZ/pygame-light2d/commit/ebd20fce4b94eb53b99ed21107a70d04731a502e). The function is a little bit faster now, but more importantly, it's much more readable. Thanks for the detailed message. Next time, you can make the changes yourself and create a pull request (if you want to); this way you will be shown as a contributor on GitHub. 

Btw, I have a shader library for Pygame, [pygame-render](https://github.com/MarkelZ/pygame-render), thought you would find it interesting :)
